# .github/workflows/use-scanner.yml dans le repo de ton app
name: Scanner de sécurité centralisé

on:
  push:
    branches: [ master ]  # ou autre branche que tu veux surveiller

jobs:
  call-scanner:
    uses: B-BRAHIM433/Stage_DevSecOps/.github/workflows/scan_app.yml@main
    with:
      docker_image: ""  # ou vide si tu ne veux que le code
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
